<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Calon_siswa_model extends CI_Model
{

    public $table = 'calon_siswa';
    public $id = 'id_siswabaru';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where('id_user', $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_siswabaru', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('nama_siswa', $q);
	$this->db->or_like('tempat_lahir', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('bulan', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('alamat_lengkap', $q);
	$this->db->or_like('kode_pos', $q);
	$this->db->or_like('asal_sekolah', $q);
	$this->db->or_like('alamat_sekolah', $q);
	$this->db->or_like('tahun_lulus', $q);
	$this->db->or_like('no_ijazah', $q);
	$this->db->or_like('nisn', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('email', $q);
	$this->db->or_like('nilai_unmatematika', $q);
	$this->db->or_like('nilai_unbinggris', $q);
	$this->db->or_like('nilai_unbindonesia', $q);
	$this->db->or_like('upload_kk', $q);
	$this->db->or_like('upload_aktekelahiran', $q);
	$this->db->or_like('upload_skl', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select("c.*,p.status_validasi_berkas");
        $this->db->from('calon_siswa c');
        $this->db->join('pendaftaran p', 'c.id_siswabaru=p.id_siswabaru', 'left');
        $this->db->group_by('c.id_siswabaru');
        $this->db->order_by($this->id, $this->order);
        
	
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        $insert_id = $this->db->insert_id();

   return  $insert_id;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where('id_siswabaru', $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk(){
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data); 
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }

}

/* End of file Calon_siswa_model.php */
/* Location: ./application/models/Calon_siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-07-13 18:30:07 */
/* http://harviacode.com */